"""
LLM PROVIDER — Multi-Model AI Abstraction Layer for Bug Bounty Agents.

Provides a unified interface for all 10 agents to call LLMs for reasoning,
analysis, and decision-making. Supports multiple providers:
  - OpenAI GPT-4o (primary reasoning)
  - Anthropic Claude 3.5 Sonnet (analysis & reporting)
  - Local Ollama (offline/air-gapped fallback)

Architecture:
  LLMProvider (interface)
    ├── OpenAILLM     → api.openai.com
    ├── ClaudeLLM     → api.anthropic.com
    └── OllamaLLM     → localhost:11434

Usage by agents:
  provider = LLMProvider.get_default()
  analysis = await provider.analyze_finding(finding)
  severity = await provider.score_cvss(evidence)
"""

import json
import os
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

# ── Configuration ───────────────────────────────────────────────────────────

class LLMProviderType(str, Enum):
    OPENAI = "openai"
    CLAUDE = "claude"
    OLLAMA = "ollama"
    AUTO = "auto"  # Try providers in order of capability


@dataclass
class LLMConfig:
    """Configuration for an LLM provider."""
    provider_type: LLMProviderType = LLMProviderType.AUTO
    model: str = ""
    api_key: str = ""
    api_base: str = ""
    temperature: float = 0.1  # Low temp for deterministic security analysis
    max_tokens: int = 4096
    timeout_seconds: int = 60

    @classmethod
    def from_env(cls) -> "LLMConfig":
        """Load config from environment variables with sensible defaults."""
        # Try OpenAI first (most capable)
        if os.environ.get("OPENAI_API_KEY"):
            return cls(
                provider_type=LLMProviderType.OPENAI,
                model=os.environ.get("OPENAI_MODEL", "gpt-4o"),
                api_key=os.environ["OPENAI_API_KEY"],
                api_base=os.environ.get("OPENAI_API_BASE", ""),
            )
        # Then Claude
        if os.environ.get("ANTHROPIC_API_KEY"):
            return cls(
                provider_type=LLMProviderType.CLAUDE,
                model=os.environ.get("ANTHROPIC_MODEL", "claude-3-5-sonnet-20241022"),
                api_key=os.environ["ANTHROPIC_API_KEY"],
                api_base=os.environ.get("ANTHROPIC_API_BASE", ""),
            )
        # Fallback to Ollama (local)
        return cls(
            provider_type=LLMProviderType.OLLAMA,
            model=os.environ.get("OLLAMA_MODEL", "llama3.2"),
            api_base=os.environ.get("OLLAMA_API_BASE", "http://localhost:11434"),
        )


# ── Structured Output Schemas ───────────────────────────────────────────────

@dataclass
class LLMAnalysis:
    """Structured output from an LLM analysis call."""
    reasoning: str = ""
    confidence: float = 0.0
    classification: str = ""
    key_findings: list[str] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)
    raw_response: str = ""


@dataclass
class CVSSAssessment:
    """CVSS score derived by LLM reasoning."""
    vector_string: str = ""
    base_score: float = 0.0
    severity: str = "None"
    attack_vector: str = ""
    attack_complexity: str = ""
    privileges_required: str = ""
    user_interaction: str = ""
    scope: str = ""
    confidentiality: str = ""
    integrity: str = ""
    availability: str = ""
    reasoning: str = ""


@dataclass
class VulnerabilityHypothesis:
    """A hypothesis generated by LLM reasoning about potential vulnerabilities."""
    vulnerability_type: str = ""
    likelihood: str = "MEDIUM"  # LOW / MEDIUM / HIGH
    affected_endpoint: str = ""
    reasoning: str = ""
    suggested_payloads: list[str] = field(default_factory=list)
    expected_indicators: list[str] = field(default_factory=list)
    priority_score: float = 0.0


# ── LLM Reasoning Prompt Templates ──────────────────────────────────────────

class PromptTemplates:
    """Collection of prompt templates for different analysis types."""

    ASSET_PRIORITIZATION = """You are a Bug Bounty Asset Prioritization Analyst.
Given this target intelligence, score each asset 0-100 for testing priority.

Program Context: {program_context}
Discovered Assets: {assets_json}
Technology Stack: {technologies_json}

Consider:
- Business criticality (public-facing, auth-protected, data-processing)
- Attack surface exposure (API surface, admin panels, file uploads)
- Reward potential (high-value bugs often in auth, payment, data access flows)
- Authentication boundaries (bypass potential)
- Data sensitivity (PII, financial, health data)

Return ONLY a JSON array of objects with fields: asset_name, priority_score, reasoning[].
"""

    VULNERABILITY_HYPOTHESIS = """You are an Adversarial Vulnerability Hypothesis Generator.
Given this attack surface intelligence, generate the most likely vulnerability hypotheses.

Target: {target}
Technology: {technology_stack}
Endpoints: {endpoints_json}
Historical Findings: {historical_findings}

For each hypothesis include:
- vulnerability_type: OWASP category
- likelihood: LOW/MEDIUM/HIGH based on evidence
- affected_endpoint: specific URL/path
- reasoning: chain of evidence leading to this hypothesis
- suggested_payloads: 1-3 test payloads
- expected_indicators: what to look for in responses

Return ONLY a JSON array of hypothesis objects.
"""

    FALSE_POSITIVE_ANALYSIS = """You are a Skeptical Security Validator.
Your job is to FALSIFY findings before they are reported.

Finding Title: {finding_title}
Vulnerability Type: {vuln_type}
Target: {target}
Evidence Provided: {evidence_json}
Reproduction Steps: {steps_json}

Generate at least 5 alternative explanations for the observed behavior:
1. Could this be a false positive? Why?
2. What other explanations exist for the observed behavior?
3. What evidence would confirm this is a real vulnerability?
4. What evidence would disprove this finding?
5. Is the impact realistic or inflated?

Return ONLY a JSON object with fields:
- false_positive_likelihood: 0-100
- alternative_explanations: string[]
- missing_evidence: string[]
- recommended_action: "ESCALATE" | "INVESTIGATE_DEEPER" | "REJECT"
- confidence: 0.0-1.0
- reasoning: string
"""

    CVSS_SCORING = """You are a CVSS 3.1 Scoring Specialist.
Given this vulnerability evidence, calculate an accurate CVSS score.

Vulnerability Type: {vuln_type}
Target: {target}
Description: {description}
Impact Evidence: {impact_evidence}
Attack Prerequisites: {prerequisites}

Consider all CVSS 3.1 metrics:
- Attack Vector (AV): Network/Adjacent/Local/Physical
- Attack Complexity (AC): Low/High
- Privileges Required (PR): None/Low/High
- User Interaction (UI): None/Required
- Scope (S): Unchanged/Changed
- Confidentiality (C): None/Low/High
- Integrity (I): None/Low/High
- Availability (A): None/Low/High

Return ONLY a JSON object with each metric and a vector_string.
"""

    PROGRAM_INTELLIGENCE = """You are a Bug Bounty Program Intelligence Analyst.
Analyze this bug bounty program content and extract structured intelligence.

Program URL: {url}
Page Content: {content_preview}
(Content length: {content_length} chars)

Extract the following structured data:
1. Program metadata: platform, program_name, organization, status
2. In-scope assets: every domain, subdomain, API, mobile app
3. Out-of-scope assets: explicitly excluded targets
4. Accepted vulnerability types: what they pay for
5. Rejected vulnerability types: what they don't accept
6. Testing restrictions: rate limits, prohibited methods
7. Reward structure: min/max payouts, severity mapping
8. Program maturity: response quality, scope clarity, policy clarity

Return ONLY a JSON object with these fields. When uncertain, use null or empty arrays.
"""

    POLICY_DECISION = """You are a Bug Bounty Policy Enforcement Agent.
Evaluate whether this finding should be ALLOWED, REVIEWED, or REJECTED.

Finding: {finding_json}
Program Policy: {policy_json}
Accepted Vuln Types: {accepted_types}
Rejected Vuln Types: {rejected_types}

Consider:
1. Is the target in scope?
2. Is the vulnerability type accepted?
3. Is the evidence sufficient?
4. Is the impact demonstrated?
5. Is there any policy violation?

Return ONLY a JSON object:
{
    "decision": "ALLOW" | "REVIEW" | "REJECT",
    "confidence": 0.0-1.0,
    "reasoning": "...",
    "policy_citations": ["..."],
    "missing_evidence": ["..."],
    "recommended_action": "..."
}
"""

    SCOPE_AUTHORIZATION = """You are a Bug Bounty Scope Guardian.
Authorize or deny access to the following target.

Target: {target}
Program Scope: {scope_json}
Owned Domains: {owned_domains}
Third-Party Domains: {third_party}

Consider:
1. Is this target explicitly in scope?
2. Is it explicitly out of scope?
3. Could it be a subdomain requiring wildcard authorization?
4. Is this likely a third-party or unrelated service?

Return ONLY a JSON object:
{
    "decision": "ALLOW" | "REVIEW" | "BLOCK",
    "authorization_confidence": 0.0-1.0,
    "reasoning": "...",
    "uncertainties": ["..."],
    "recommended_next_action": "..."
}
"""

    OSINT_ANALYSIS = """You are a Passive Reconnaissance Intelligence Analyst.
Analyze this OSINT data and extract actionable intelligence.

Target: {target}
Source Data: {osint_data}
Tools Used: {tools_used}

Extract:
1. Attack surface entries: discovered subdomains, endpoints, technologies
2. Priority targets: high-value assets for testing
3. Technology stack: frameworks, servers, languages detected
4. Security posture: WAF, CDN, security headers observed
5. Recommendations: what to test first and why

Return ONLY a JSON object with these fields.
"""

    EXPLOITATION_PLANNING = """You are a Safe Exploitation Engineer.
Design a proof-of-concept for this vulnerability that demonstrates impact without causing damage.

Vulnerability: {vuln_json}
Evidence: {evidence}
Target: {target}

Design:
1. Safe PoC steps: read-only, non-destructive actions
2. Expected evidence: what responses/behavior confirm the vulnerability
3. Impact demonstration: how to show business risk without data loss
4. Reproduction script: curl commands or Python snippets

Return ONLY a JSON object with these fields as an actionable PoC plan.
"""

    REPORT_GENERATION = """You are a Professional Bug Bounty Report Writer.
Create a clear, evidence-backed vulnerability report in Blank.md format.

Finding: {finding_json}
Analysis: {analysis_json}
PoC: {poc_json}

Produce a professional report covering:
1. Title (descriptive, including vulnerability type)
2. Issue Description (technical, precise)
3. Affected URL/Area
4. Risk Rating (CVSS 3.1)
5. Impact (real, demonstrated, not inflated)
6. Attack Scenario (step-by-step)
7. Steps to Reproduce (reproducible by triager)
8. Supporting Evidence (requests, responses, screenshots)
9. Remediation Recommendation (actionable, specific)

Return ONLY the report text. No JSON wrapper.
"""


# ── LLM Provider Interface ──────────────────────────────────────────────────

class LLMProvider:
    """
    Multi-model LLM abstraction for bug bounty agents.

    Usage:
        provider = LLMProvider.get_default()
        analysis = await provider.analyze(LLMAnalysisPrompt, context)
        cvss = await provider.score_cvss(evidence)
    """

    def __init__(self, config: LLMConfig | None = None):
        self.config = config or LLMConfig.from_env()
        self._client: Any | None = None
        self._provider_type = self.config.provider_type
        self._capabilities: list[str] = ["reasoning", "analysis", "scoring", "classification"]

    # ═══════════════════════════════════════════════════════════════════════════
    # FACTORY
    # ═══════════════════════════════════════════════════════════════════════════

    @classmethod
    def get_default(cls) -> "LLMProvider":
        """Create the best available LLM provider from environment config."""
        return cls(LLMConfig.from_env())

    @classmethod
    def create(cls, provider_type: str, **kwargs) -> "LLMProvider":
        """Create a specific provider type with given config overrides."""
        config = LLMConfig.from_env()
        try:
            config.provider_type = LLMProviderType(provider_type.lower())
        except ValueError:
            config.provider_type = LLMProviderType.AUTO
        for k, v in kwargs.items():
            if hasattr(config, k):
                setattr(config, k, v)
        return cls(config)

    @property
    def is_available(self) -> bool:
        """Check if this provider can make LLM calls."""
        if self._provider_type == LLMProviderType.OPENAI or self._provider_type == LLMProviderType.CLAUDE:
            return bool(self.config.api_key)
        elif self._provider_type == LLMProviderType.OLLAMA:
            return True  # Checked at call time
        return False

    @property
    def provider_name(self) -> str:
        """Human-readable provider name."""
        names = {
            LLMProviderType.OPENAI: f"OpenAI ({self.config.model})",
            LLMProviderType.CLAUDE: f"Claude ({self.config.model})",
            LLMProviderType.OLLAMA: f"Ollama ({self.config.model})",
            LLMProviderType.AUTO: "Auto",
        }
        return names.get(self._provider_type, "Unknown")

    # ═══════════════════════════════════════════════════════════════════════════
    # CORE REASONING API
    # ═══════════════════════════════════════════════════════════════════════════

    async def reason(
        self,
        prompt: str,
        system_prompt: str = "",
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> str:
        """
        Core reasoning method. Send a prompt to the LLM and get text back.

        Args:
            prompt: The user/assistant prompt
            system_prompt: Optional system-level instructions
            temperature: Override default temperature
            max_tokens: Override default max tokens

        Returns:
            Raw text response from the LLM
        """
        if self._provider_type == LLMProviderType.OPENAI:
            return await self._call_openai(prompt, system_prompt, temperature, max_tokens)
        elif self._provider_type == LLMProviderType.CLAUDE:
            return await self._call_claude(prompt, system_prompt, temperature, max_tokens)
        elif self._provider_type == LLMProviderType.OLLAMA:
            return await self._call_ollama(prompt, system_prompt, temperature, max_tokens)
        else:
            return await self._auto_provider(prompt, system_prompt, temperature, max_tokens)

    async def reason_structured(
        self,
        prompt: str,
        system_prompt: str = "",
        temperature: float | None = None,
    ) -> dict[str, Any]:
        """
        Send a prompt and parse the response as JSON.

        Used for structured outputs like CVSS scores, policy decisions, etc.
        The prompt should instruct the LLM to return ONLY a JSON object.
        """
        # Add JSON formatting instruction
        json_prompt = prompt + "\n\nIMPORTANT: Return ONLY valid JSON. No markdown, no code fences, no explanation."
        response = await self.reason(json_prompt, system_prompt, temperature or 0.05, max_tokens=4096)

        # Try to extract JSON from the response
        return self._parse_json_response(response)

    async def analyze(
        self,
        template: str,
        context: dict[str, Any],
        system_prompt: str = "",
    ) -> LLMAnalysis:
        """
        Fill a prompt template with context and get a structured analysis.

        Args:
            template: PromptTemplate string with {placeholders}
            context: Dict of values to fill placeholders
            system_prompt: Optional system instructions

        Returns:
            LLMAnalysis with reasoning, confidence, classification
        """
        prompt = template.format(**context)
        response = await self.reason(prompt, system_prompt)

        return LLMAnalysis(
            reasoning=response,
            confidence=0.7,
            classification="analyzed",
            raw_response=response,
        )

    async def analyze_structured(
        self,
        template: str,
        context: dict[str, Any],
        system_prompt: str = "",
    ) -> dict[str, Any]:
        """
        Fill a prompt template and get a structured (JSON) response.

        Args:
            template: PromptTemplate string with {placeholders}
            context: Dict of values to fill placeholders
            system_prompt: Optional system instructions

        Returns:
            Parsed JSON dict from the LLM response
        """
        prompt = template.format(**context)
        return await self.reason_structured(prompt, system_prompt)

    # ═══════════════════════════════════════════════════════════════════════════
    # SPECIALIZED ANALYSIS METHODS
    # ═══════════════════════════════════════════════════════════════════════════

    async def prioritize_assets(
        self,
        program_context: str,
        assets: list[dict[str, Any]],
        technologies: list[str],
    ) -> list[dict[str, Any]]:
        """Use LLM to prioritize discovered assets by testing value."""
        context = {
            "program_context": program_context[:2000],
            "assets_json": json.dumps(assets, indent=2)[:3000],
            "technologies_json": json.dumps(technologies, indent=2)[:1000],
        }
        result = await self.analyze_structured(PromptTemplates.ASSET_PRIORITIZATION, context)
        if isinstance(result, list):
            return result
        return result.get("assets", result.get("priorities", []))

    async def generate_hypotheses(
        self,
        target: str,
        technology_stack: list[str],
        endpoints: list[str],
        historical_findings: list[str],
    ) -> list[VulnerabilityHypothesis]:
        """Generate vulnerability hypotheses for a target."""
        context = {
            "target": target,
            "technology_stack": ", ".join(technology_stack[:20]),
            "endpoints_json": json.dumps(endpoints[:30], indent=2),
            "historical_findings": json.dumps(historical_findings[:20], indent=2),
        }
        result = await self.analyze_structured(PromptTemplates.VULNERABILITY_HYPOTHESIS, context)
        if isinstance(result, list):
            return [VulnerabilityHypothesis(**h) for h in result if isinstance(h, dict)]
        return [VulnerabilityHypothesis(**h) for h in result.get("hypotheses", []) if isinstance(h, dict)]

    async def analyze_false_positive(
        self,
        finding_title: str,
        vuln_type: str,
        target: str,
        evidence: dict[str, Any],
        steps: list[str],
    ) -> dict[str, Any]:
        """Use LLM to analyze whether a finding is a false positive."""
        context = {
            "finding_title": finding_title,
            "vuln_type": vuln_type,
            "target": target,
            "evidence_json": json.dumps(evidence, indent=2)[:3000],
            "steps_json": json.dumps(steps, indent=2)[:2000],
        }
        return await self.analyze_structured(PromptTemplates.FALSE_POSITIVE_ANALYSIS, context)

    async def score_cvss(
        self,
        vuln_type: str,
        target: str,
        description: str,
        impact_evidence: str,
        prerequisites: str = "",
    ) -> CVSSAssessment:
        """Use LLM to calculate CVSS 3.1 score."""
        context = {
            "vuln_type": vuln_type,
            "target": target,
            "description": description[:2000],
            "impact_evidence": impact_evidence[:2000],
            "prerequisites": prerequisites[:500],
        }
        result = await self.analyze_structured(PromptTemplates.CVSS_SCORING, context)
        return CVSSAssessment(
            vector_string=result.get("vector_string", ""),
            base_score=float(result.get("base_score", result.get("score", 0))),
            severity=result.get("severity", "None"),
            attack_vector=result.get("attack_vector", result.get("AV", "")),
            attack_complexity=result.get("attack_complexity", result.get("AC", "")),
            privileges_required=result.get("privileges_required", result.get("PR", "")),
            user_interaction=result.get("user_interaction", result.get("UI", "")),
            scope=result.get("scope", result.get("S", "")),
            confidentiality=result.get("confidentiality", result.get("C", "")),
            integrity=result.get("integrity", result.get("I", "")),
            availability=result.get("availability", result.get("A", "")),
            reasoning=result.get("reasoning", ""),
        )

    async def analyze_program(
        self,
        url: str,
        content: str,
    ) -> dict[str, Any]:
        """Use LLM to analyze a bug bounty program page."""
        context = {
            "url": url,
            "content_preview": content[:8000],
            "content_length": len(content),
        }
        return await self.analyze_structured(PromptTemplates.PROGRAM_INTELLIGENCE, context)

    async def make_policy_decision(
        self,
        finding: dict[str, Any],
        policy: dict[str, Any],
        accepted_types: list[str],
        rejected_types: list[str],
    ) -> dict[str, Any]:
        """Use LLM to make a policy enforcement decision."""
        context = {
            "finding_json": json.dumps(finding, indent=2)[:3000],
            "policy_json": json.dumps(policy, indent=2)[:3000],
            "accepted_types": json.dumps(accepted_types),
            "rejected_types": json.dumps(rejected_types),
        }
        return await self.analyze_structured(PromptTemplates.POLICY_DECISION, context)

    async def authorize_scope(
        self,
        target: str,
        scope: dict[str, Any],
        owned_domains: list[str],
        third_party: list[str],
    ) -> dict[str, Any]:
        """Use LLM to authorize/deny scope access."""
        context = {
            "target": target,
            "scope_json": json.dumps(scope, indent=2)[:3000],
            "owned_domains": json.dumps(owned_domains),
            "third_party": json.dumps(third_party),
        }
        return await self.analyze_structured(PromptTemplates.SCOPE_AUTHORIZATION, context)

    async def analyze_osint(
        self,
        target: str,
        osint_data: dict[str, Any],
        tools_used: list[str],
    ) -> dict[str, Any]:
        """Use LLM to analyze OSINT data and extract actionable intelligence."""
        context = {
            "target": target,
            "osint_data": json.dumps(osint_data, indent=2)[:5000],
            "tools_used": json.dumps(list(tools_used)[:20]),
        }
        return await self.analyze_structured(PromptTemplates.OSINT_ANALYSIS, context)

    async def plan_exploitation(
        self,
        vuln_json: dict[str, Any],
        evidence: dict[str, Any],
        target: str,
    ) -> dict[str, Any]:
        """Use LLM to design a safe proof-of-concept."""
        context = {
            "vuln_json": json.dumps(vuln_json, indent=2)[:3000],
            "evidence": json.dumps(evidence, indent=2)[:3000],
            "target": target,
        }
        return await self.analyze_structured(PromptTemplates.EXPLOITATION_PLANNING, context)

    async def write_report(
        self,
        finding: dict[str, Any],
        analysis: dict[str, Any],
        poc: dict[str, Any],
    ) -> str:
        """Use LLM to generate a professional vulnerability report."""
        context = {
            "finding_json": json.dumps(finding, indent=2)[:4000],
            "analysis_json": json.dumps(analysis, indent=2)[:4000],
            "poc_json": json.dumps(poc, indent=2)[:4000],
        }
        prompt = PromptTemplates.REPORT_GENERATION.format(**context)
        return await self.reason(
            prompt,
            system_prompt=(
                "You are a professional bug bounty report writer. "
                "Write clear, evidence-backed, actionable reports. "
                "Be precise, not verbose. Never exaggerate impact."
            ),
            temperature=0.3,
            max_tokens=8192,
        )

    # ═══════════════════════════════════════════════════════════════════════════
    # PROVIDER IMPLEMENTATIONS
    # ═══════════════════════════════════════════════════════════════════════════

    async def _call_openai(
        self,
        prompt: str,
        system_prompt: str,
        temperature: float | None,
        max_tokens: int | None,
    ) -> str:
        """Call OpenAI API."""
        try:
            import httpx
            api_key = self.config.api_key
            if not api_key:
                return self._fallback_response("No OpenAI API key configured")

            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            }
            base = self.config.api_base or "https://api.openai.com/v1"
            payload = {
                "model": self.config.model or "gpt-4o",
                "messages": [
                    {"role": "system", "content": system_prompt or "You are a security research assistant."},
                    {"role": "user", "content": prompt},
                ],
                "temperature": temperature if temperature is not None else self.config.temperature,
                "max_tokens": max_tokens or self.config.max_tokens,
            }

            async with httpx.AsyncClient(timeout=self.config.timeout_seconds) as client:
                resp = await client.post(f"{base}/chat/completions", json=payload, headers=headers)

            if resp.status_code == 200:
                data = resp.json()
                return data["choices"][0]["message"]["content"]
            else:
                return self._fallback_response(f"OpenAI API error: {resp.status_code}")

        except ImportError:
            return self._fallback_response("httpx not installed for OpenAI calls")
        except Exception as e:
            return self._fallback_response(f"OpenAI call failed: {str(e)[:100]}")

    async def _call_claude(
        self,
        prompt: str,
        system_prompt: str,
        temperature: float | None,
        max_tokens: int | None,
    ) -> str:
        """Call Anthropic Claude API."""
        try:
            import httpx
            api_key = self.config.api_key
            if not api_key:
                return self._fallback_response("No Anthropic API key configured")

            headers = {
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "Content-Type": "application/json",
            }
            base = self.config.api_base or "https://api.anthropic.com/v1"
            payload = {
                "model": self.config.model or "claude-3-5-sonnet-20241022",
                "max_tokens": max_tokens or self.config.max_tokens,
                "system": system_prompt or "You are a security research assistant.",
                "messages": [{"role": "user", "content": prompt}],
            }

            async with httpx.AsyncClient(timeout=self.config.timeout_seconds) as client:
                resp = await client.post(f"{base}/messages", json=payload, headers=headers)

            if resp.status_code == 200:
                data = resp.json()
                return data["content"][0]["text"]
            else:
                return self._fallback_response(f"Claude API error: {resp.status_code}")

        except ImportError:
            return self._fallback_response("httpx not installed for Claude calls")
        except Exception as e:
            return self._fallback_response(f"Claude call failed: {str(e)[:100]}")

    async def _call_ollama(
        self,
        prompt: str,
        system_prompt: str,
        temperature: float | None,
        max_tokens: int | None,
    ) -> str:
        """Call local Ollama instance."""
        try:
            import httpx
            base = self.config.api_base or "http://localhost:11434"
            payload = {
                "model": self.config.model or "llama3.2",
                "prompt": prompt,
                "system": system_prompt or "",
                "stream": False,
                "options": {
                    "temperature": temperature if temperature is not None else self.config.temperature,
                    "num_predict": max_tokens or self.config.max_tokens,
                },
            }

            async with httpx.AsyncClient(timeout=self.config.timeout_seconds) as client:
                resp = await client.post(f"{base}/api/generate", json=payload)

            if resp.status_code == 200:
                data = resp.json()
                return data.get("response", "")
            else:
                return self._fallback_response(f"Ollama API error: {resp.status_code}")

        except (ImportError, Exception) as e:
            return self._fallback_response(f"Ollama call failed: {str(e)[:100]}")

    async def _auto_provider(
        self,
        prompt: str,
        system_prompt: str,
        temperature: float | None,
        max_tokens: int | None,
    ) -> str:
        """Try providers in order: OpenAI → Claude → Ollama."""
        # Try OpenAI first
        openai_key = self.config.api_key if self._provider_type == LLMProviderType.OPENAI else os.environ.get("OPENAI_API_KEY")
        if openai_key:
            result = await self._call_openai(prompt, system_prompt, temperature, max_tokens)
            if not result.startswith("[LLM Fallback"):
                return result

        # Try Claude
        claude_key = self.config.api_key if self._provider_type == LLMProviderType.CLAUDE else os.environ.get("ANTHROPIC_API_KEY")
        if claude_key:
            result = await self._call_claude(prompt, system_prompt, temperature, max_tokens)
            if not result.startswith("[LLM Fallback"):
                return result

        # Fallback to Ollama
        return await self._call_ollama(prompt, system_prompt, temperature, max_tokens)

    # ═══════════════════════════════════════════════════════════════════════════
    # HELPERS
    # ═══════════════════════════════════════════════════════════════════════════

    def _fallback_response(self, reason: str) -> str:
        """Return a structured fallback response when LLM is unavailable."""
        return f"[LLM Fallback: {reason}]"

    def _parse_json_response(self, response: str) -> dict[str, Any]:
        """Extract JSON from an LLM response, handling markdown fences and extra text."""
        if not response:
            return {}

        # Remove markdown code fences
        cleaned = re.sub(r'```(?:json)?\s*\n?', '', response).strip()

        # Try to find JSON object/array boundaries
        for start_char, end_char in [('{', '}'), ('[', ']')]:
            start_idx = cleaned.find(start_char)
            if start_idx >= 0:
                end_idx = cleaned.rfind(end_char)
                if end_idx > start_idx:
                    json_str = cleaned[start_idx:end_idx + 1]
                    try:
                        return json.loads(json_str)
                    except json.JSONDecodeError:
                        continue

        # Last resort: try parsing the whole cleaned string
        try:
            return json.loads(cleaned)
        except json.JSONDecodeError:
            return {"raw_response": response[:500]}

    def truncate_for_context(self, text: str, max_chars: int = 4000) -> str:
        """Truncate text to fit within LLM context limits."""
        if len(text) <= max_chars:
            return text
        return text[:max_chars] + f"\n... [truncated, {len(text) - max_chars} more chars]"


# ── Convenience Factory ─────────────────────────────────────────────────────

_default_provider: LLMProvider | None = None


def get_llm_provider() -> LLMProvider:
    """Get or create the default LLM provider singleton."""
    global _default_provider
    if _default_provider is None:
        _default_provider = LLMProvider.get_default()
    return _default_provider
